### ISSUE TITLE
Does not find new files in library directories

### ISSUE THREAD

**Issue by Stopka** [MediaBrowser/Emby.Build#70]
I migrated from linux emby installation to docker container running on linux and have one problem I could not solve.  On initial setup of library directories it scanned and added all files, but now when I add new file it is not found. The realtime monitoring of the directory is on, and it doesn't find new files even when i schedule library scan manually. The only way i managed to add new files to library was to delete library dir setting and then add it again.

# Docker compose

```
version: "3.3"
services:
  (...)
  emby:
    image: emby/embyserver:latest
    volumes:
      - emby-data:/config
      - <musicdir>:/mnt/Music:ro
      - <filmdir>:/mnt/Film
      - <seriesdir>:/mnt/Serial
    environment:
      - UID=422
      - GID=422
    network_mode: host
    ports:
      - 8096:8096
(...)
volumes:
  emby-data:
  (...)
```

UID:GID belongs to emby:emby user group on host system. This is the same user that native emby installation used and that has permisson to read files and read+use dirs on mounted directories (using ACL).

# Versions
Emby: 3.3.1.0
Docker: 18.02.0-ce, build fc4de447b5
Docker-compose: 1.19.0
OS: Arch Linux

## Docker version
```
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.4
 Git commit:	fc4de447b5
 Built:	Tue Feb 13 15:28:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	fc4de447b5
  Built:	Tue Feb 13 15:28:34 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```
## Docker info
```
Containers: 20
 Running: 20
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 18.02.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.15.10-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.36GiB
Name:  <name>
ID: <...>
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
